version: "3.8" # Specify the Compose file version

services:
  core-app: # Define the service name
    build:
      context: . # Use the Dockerfile in the current directory (backend/core)
      dockerfile: Dockerfile # Specify the Dockerfile name
    ports:
      - "5555:5555" # Map host port 5555 to container port 5555
    env_file:
      - .env # Load environment variables from the .env file in the same directory
    environment:
      # Define environment variables directly
      PORT: 5555
    restart: unless-stopped # Restart policy
